config/routes.rb
Rails.application.routes.draw do
  root "events#index"

  resources :events do
    member do
      get :add_relevence
      get :sub_relevence
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :message, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to events_path
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to events_path
    else
      render :edit
    end
  end

  def destroy
    Event.find(params[:id]).destroy
    redirect_to events_path
  end

  def add_relevence
    @event = Event.find(params[:id])
    @event.relevence += 1
    @event.save
    redirect_to event_path(@event)
  end

  def sub_relevence
    @event = Event.find(params[:id])
    @event.relevence -= 1
    @event.save
    redirect_to event_path(@event)
  end

  private

  def event_params
    params.require(:event).permit(:message, :relevence)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_form.html.erb
<%= form_for @event do |form| %>
  <% if @event.errors.any? %>
    <% @event.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>

  <%= form.label :message %>
  <%= form.text_field :message %>

  <%= form.label :relevence %>
  <%= form.number_field :relevence %>

  <%= submit_tag "Save" %>
<% end %>

app/views/events/edit.html.erb
<%= render partial: "form", event: @event %>

app/views/events/index.html.erb
<h1>Events</h1>
<%= link_to "New Event", new_event_path %>
<% @events.each do |event| %>
  <p>
    <strong><%= event.message %></strong>
    <%= event.relevence %>
    <%= event.created_at %>
    <%= link_to "Show", event_path(event) %>
    <%= link_to "Edit", edit_event_path(event) %>
    <%= link_to "Delete", event_path(event), method: :delete %>
  </p>
<% end %>

app/views/events/new.html.erb
<%= render partial: "form", event: @event %>

app/views/events/show.html.erb
<h1><%= @event.message %></h1>
<h6>Relevence: <%= @event.relevence %></h6>
<h6>Created at <%= @event.created_at %></h6>
<%= link_to "Increment relevence", add_relevence_event_path(@event) %>
<%= link_to "Decrement relevence", sub_relevence_event_path(@event) %>
<%= link_to "Delete", event_path(@event), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimelineApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>